<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    
    <script>
    
        /*
            Promise
                构造函数
                接受一个参数：callback，我们把要执行的异步任务放置在这个callback中

                Promise对象内部会维护一个状态
                    默认是：pending
                    成功：resolved
                    失败：rejected

                Promise对象下有一个方法：then，该方法在Promise对象的状态发生改变的时候触发then的回调
        */

        let p1 = new Promise( ( resolve, reject ) => {

            // 当Promise被实例化的时候，callback的异步任务就会被执行

            // 我们可以通过传入的resolve, reject，去改变当前Promise任务的状态
            // resolve, reject是两个函数，调用resolve这个函数，会把状态改成resolved，调用reject函数会把状态改成rejected
            setTimeout(() => {
                console.log(1);
                //reject();
                resolve();
            }, 1000);

        } );

        // then会接受两个参数：这两个参数都是回调，当对应的promise对象的状态变成了resolved，那么then的第一个callback就会被执行，如果状态变成了rejected，那么then的第二个callback就会被执行
        // let p2 = p1.then( () => {
        //     console.log('成功');
        // }, () => {
        //     console.log('失败');
        // } );

        // console.log(p1)

        // p1.then(() => {
        //     console.log(2);
        // },() => {
        //     console.log('a');
        //     // return new Promise((resolve, reject) => {
        //     //     reject();
        //     // });

        //     //上面的简化写法
        //     return Promise.reject();
        // }).then(() => {
        //     console.log(3);
        // },() => {
        //     console.log('b');
        // }).then(() => {
        //     console.log(4);
        // },() => {
        //     console.log('c');
        // });


        p1.then(() => {
            console.log(2);
        },() => {
            console.log('a');
            return Promise.resolve();
        }).then(() => {
            console.log(3);
        }).then(() => {
            console.log(4);
        }).catch(err => {
            // catch和then也会返回一个默认resolved状态的promise对象
            console.log('错了');
        }).then(() => {
            console.log(5);
        });
    
    
    </script>

</body>
</html>